spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

  error:
    include-stacktrace: never
    include-message: never