spring:
  application:
    name: order-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8082

  error:
    include-stacktrace: never

catalog:
  service:
    url: http://localhost:8081